# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
x = s.split()
print(x)

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [1]:
planet = "Earth"
diameter = 12742

In [3]:
x="The diameter of {planet} is {diameter} kilometers."
print(x.format(planet="Earth",diameter=12742))

The diameter of Earth is 12742 kilometers.

## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [17]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [12]:
array10=np.zeros(10)
print("Array of 10 Zeros:",array10)

Array of 10 Zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [13]:
array5=np.ones(10)*5
print("Array of 10 fives:",array5)

Array of 10 fives: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

## 5. Create an array of all the even integers from 20 to 35

In [14]:
arrayeven=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35:",arrayeven)

Array of all the even integers from 20 to 35: [20 22 24 26 28 30 32 34]

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [20]:
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
ab = np.concatenate((a,b))
print(ab)

[1 2 3 4 5 6]

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [24]:
import pandas as pd

In [25]:
data = {'Name':['Tom','Arun','Krish'],'Age':[20,21,19]}
df=pd.DataFrame(data)
print(df)

    Name  Age
0    Tom   20
1   Arun   21
2  Krish   19

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [28]:
pd.date_range(start='1/1/2023', end='2/10/2023')

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [31]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [32]:
df = pd.DataFrame(lists)
print(df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24